import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Todo app",
  description: "Generated by Vivek Roy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-[#000000de]`}
      >
        <ClerkProvider>
          <Toaster richColors position="bottom-right" />
          {children}
        </ClerkProvider>
        
      </body>
    </html>
  );
}
